apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-tls
  namespace: postgres
spec:
  secretName: postgres-tls
  secretTemplate:
    labels:
      cnpg.io/reload: ""
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - postgres.cbc.gewis.nl
