apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: postgres
spec:
  instances: 3
  enableSuperuserAccess: false
  primaryUpdateMethod: switchover

  storage:
    storageClass: longhorn-single
    size: 50Gi

  certificates:
    serverTLSSecret: postgres-tls
    serverCASecret: postgres-server-ca

  postgresql:
    parameters:
      tcp_keepalives_idle: "60"
      tcp_keepalives_interval: "10"
      tcp_keepalives_count: "3"
      idle_in_transaction_session_timeout: "60000"
    pg_hba:
      - hostnossl all all all reject

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: postgres

  bootstrap:
    initdb:
      database: provisioner
      owner: provisioner

  managed:
    roles:
      - name: provisioner
        login: true
        createdb: true
        createrole: true
    services:
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: postgres-lan
              annotations:
                lbipam.cilium.io/ips: 10.82.50.12
            spec:
              type: LoadBalancer

  inheritedMetadata:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9187"
