apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-db
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: postgres
    kind: SecretStore
  target:
    name: authentik-db
  data:
    - secretKey: AUTHENTIK_POSTGRESQL__HOST
      remoteRef:
        key: authentik/authentik
        property: host
    - secretKey: AUTHENTIK_POSTGRESQL__PORT
      remoteRef:
        key: authentik/authentik
        property: port
    - secretKey: AUTHENTIK_POSTGRESQL__NAME
      remoteRef:
        key: authentik/authentik
        property: dbname
    - secretKey: AUTHENTIK_POSTGRESQL__USER
      remoteRef:
        key: authentik/authentik
        property: username
    - secretKey: AUTHENTIK_POSTGRESQL__PASSWORD
      remoteRef:
        key: authentik/authentik
        property: password
