keys:
  admins: &admins
    - &admin_luuk ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHnm7ME9L/KuEGbSbzPJ4uVgsNl579UCCtXAIlWNYq7x
  hosts:
    - &pcgewisinfo age1hde6y6ee9g0pnvgdluxjj6xq4plrsdq8f7mf4yv6xn465ucpw3hq47heg0
    - &s3_01 age1r9nz065avdtvrx2rqyq5lztf53dw8ds0uvkxkuw2zgvkqqx5e9js347zqu

creation_rules:
  - path_regex: secrets/tofu\.yaml$
    key_groups:
      - age: *admins
  - path_regex: secrets/talos\.yaml$
    key_groups:
      - age: *admins
  - path_regex: secrets/pcgewisinfo\.yaml$
    key_groups:
      - age:
          - *pcgewisinfo
  - path_regex: secrets/s3-01\.yaml$
    key_groups:
      - age:
          - *admin_luuk
          - *s3_01
