apiVersion: v1
kind: Service
metadata:
  name: dns
  namespace: dns
spec:
  clusterIP: 10.96.0.53
  selector:
    app.kubernetes.io/name: dns
  ports:
    - name: dns
      port: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: dns-lan
  namespace: dns
  annotations:
    lbipam.cilium.io/ips: 10.82.50.201
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: dns
  ports:
    - name: dns
      port: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      protocol: TCP
