---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openbao-seal
  namespace: openbao
spec:
  encryptedData:
    key: AgApfs/4VJp6m4UjBgwhWH1rOckeX0+y5dohAPL0ZVGkLFfFTuE9ecyemfD8Erlt809Wf7ZVft0yzwmELyQrUAiq2mfDFTbO7UsN625Isul5rnqmw3C8vwKNLrOTU8saWQjOITQDWjNSxzGIelwypjIxwlmtYN+g/fuUwjLvSnWKVCZBJ95GH5N6T9nexFHws8QiAwO+/FrQeJDuDiW43PWLNBMzqt+VtVWR2krJtwG66UUEbeuaNAQ05ERBxDsl01JlIexKkw3x1HKvui2i2tcnQDrFV4wHYwu19KJSUSfzmDx4nPuChEdLf3ReMQEWcd+yPKQ6GXt9hHfIcHFPmCf1Zq31MfU0grkFhejyMrJEmJ3sBMcM2HvP7iJa2HCuWpX6l3/TECtCqoqufuq6fXddrXCtesgtDbBT/ZbikBIcxATURZ55WArlwSuWn7ri+XNrzNmR4tKsUKRVDQyiN0BtWaCXC39QCi6sdWSEgemZaRNPaFMbsjbM9MtP77jNowAQJNMQYxx0BbotKJrPpPEVjLEbrJLxrv6yzetNoG+N72blRa9B54NobPMpXiGiF20z7xCQoZd7Dh4ANDTmEG34NzSbTnXhM0oEhrYKDFZrcc/C4XP64AsYfedRK9S0lz/UdaEZSI5skFdZXuCB7W0q/gZPFeksznatt7FRNh3/HcZt69IsQziE+glTWQ16ub7m6t//4v0RRtw+aPcrocqb5zIiAuinq0a9ymi44qbKyFx9j5/IWCHw4z4xig==
  template:
    metadata:
      name: openbao-seal
      namespace: openbao
