apiVersion: v1
kind: ServiceAccount
metadata:
  name: seaweedfs
  namespace: mariadb
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: seaweedfs
  namespace: mariadb
spec:
  provider:
    vault:
      server: http://openbao-active.openbao.svc:8200
      path: seaweedfs
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: seaweedfs-mariadb
          serviceAccountRef:
            name: seaweedfs
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mariadb-s3
  namespace: mariadb
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: seaweedfs
    kind: SecretStore
  target:
    name: mariadb-s3
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: mariadb/mariadb
        property: access_key_id
    - secretKey: SECRET_ACCESS_KEY
      remoteRef:
        key: mariadb/mariadb
        property: secret_access_key
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: PhysicalBackup
metadata:
  name: mariadb-daily
  namespace: mariadb
spec:
  mariaDbRef:
    name: mariadb
  schedule:
    cron: "0 3 * * *"
    immediate: true
  target: PreferReplica
  compression: gzip
  maxRetention: 720h
  args:
    - --disable-ssl-verify-server-cert
  storage:
    s3:
      bucket: mariadb
      prefix: base
      endpoint: s3.net.gewis.nl:8333
      region: us-east-1
      accessKeyIdSecretKeyRef:
        name: mariadb-s3
        key: ACCESS_KEY_ID
      secretAccessKeySecretKeyRef:
        name: mariadb-s3
        key: SECRET_ACCESS_KEY
      tls:
        enabled: false
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: PhysicalBackup
metadata:
  name: mariadb-replica
  namespace: mariadb
spec:
  mariaDbRef:
    name: mariadb
    waitForIt: false
  schedule:
    suspend: true
  target: PreferReplica
  podAffinity: true
  timeout: 1h
  args:
    - --disable-ssl-verify-server-cert
  storage:
    s3:
      bucket: mariadb
      prefix: replica
      endpoint: s3.net.gewis.nl:8333
      region: us-east-1
      accessKeyIdSecretKeyRef:
        name: mariadb-s3
        key: ACCESS_KEY_ID
      secretAccessKeySecretKeyRef:
        name: mariadb-s3
        key: SECRET_ACCESS_KEY
      tls:
        enabled: false
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: PointInTimeRecovery
metadata:
  name: mariadb
  namespace: mariadb
spec:
  physicalBackupRef:
    name: mariadb-daily
  compression: gzip
  storage:
    s3:
      bucket: mariadb
      prefix: binlog
      endpoint: s3.net.gewis.nl:8333
      region: us-east-1
      accessKeyIdSecretKeyRef:
        name: mariadb-s3
        key: ACCESS_KEY_ID
      secretAccessKeySecretKeyRef:
        name: mariadb-s3
        key: SECRET_ACCESS_KEY
      tls:
        enabled: false
