apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mariadb-tls
  namespace: mariadb
spec:
  secretName: mariadb-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - mariadb.net.gewis.nl
