apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: postgres
spec:
  instances: 3
  enableSuperuserAccess: false

  storage:
    storageClass: longhorn-single
    size: 1Gi

  postgresql:
    parameters:
      max_wal_size: 256MB

  managed:
    roles:
      - name: provisioner
        login: true
        createdb: true
        createrole: true
        passwordSecret:
          name: provisioner-role

  inheritedMetadata:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9187"
