apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
  namespace: databases
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: postgres
  namespace: databases
spec:
  provider:
    vault:
      server: http://openbao-active.openbao.svc:8200
      path: postgres
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: postgres-cluster
          serviceAccountRef:
            name: postgres
