apiVersion: v1
kind: ServiceAccount
metadata:
  name: garage
  namespace: observability
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: garage
  namespace: observability
spec:
  provider:
    vault:
      server: http://openbao-active.openbao.svc:8200
      path: garage
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: garage-observability
          serviceAccountRef:
            name: garage
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: authentik
  namespace: observability
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: authentik
  namespace: observability
spec:
  provider:
    vault:
      server: http://openbao-active.openbao.svc:8200
      path: authentik
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: authentik-observability
          serviceAccountRef:
            name: authentik
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
  namespace: observability
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: postgres
  namespace: observability
spec:
  provider:
    vault:
      server: http://openbao-active.openbao.svc:8200
      path: postgres
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: postgres-observability
          serviceAccountRef:
            name: postgres
