---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAzg0ajgnpElyd3k27YI4EfhDhZA+fvQb9XJh0ogY6nFqPmKcl6RNjmmYpJL1uVYhufUa3RqPaU6o4KK0hJjcqC30ZO++7TEkSs81ageHcEBAAz1kCLrjexgCa2x+wXpgQfj5pBC2B9H0KM7haKI94mDRsn5MJcnB5wYZgERykUpJgdwqzZ2C7YakA7eziPtCwoxPB+GzkxDia+IZSWiUzmTcFakfKNduxG1PE68+EW7JaRpj2pXReiv2Sx0rcGy/ob35EDfyKK/JnIua2j2sJNViM0FjvnpGjI8KEkDRuq27buImAR+0gUt89oRjFbgpEKFUKFylrY5JCE5QjQ1SfC7/+zA2hSW+rQc/YHeqwZN+s5aBsBDQkh6vVr+MhqHxI8jIzt2GW9keofCmALaKYCe3QPhkw7tVHnTTrLLEv5o5cbU+sLcPEvzLx47j91gd3iFqaUSx/4UkHqRAQAdVjrAYNi6r51uzR/k30194CkWGfhVi2CLxn4klAKvzHn4HJkxy1xuuzCG6nK4hF/zwoMvhQOKVE3/qI6uVjIJQKLg7TEy8mOW3nvrbBksv/smGdEQSV19EcizpVt6ZlODraljf194vd8Z1a3b7RvYvFJvku7z/SYStkzwC/WfTMDMRclM8zULRXjBruxg2JpZvfTzGdpJcEGfP8h9AHk/bMugWqgr72w6gtlkxZ4QPYxvRQVYo0Bwh/Mfr0xUEITWRfUVo6tW3lwbOBJSYNilaiokWbGcJltbgVWyPPWJzr9nRVA8QTotw==
  template:
    metadata:
      name: cloudflare
      namespace: cert-manager
