apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: observability
spec:
  releaseName: grafana
  interval: 1h
  chart:
    spec:
      chart: grafana
      version: "12.10.4"
      sourceRef:
        kind: HelmRepository
        name: grafana-community
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    replicas: 1

    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "3000"

    deploymentStrategy:
      type: Recreate

    persistence:
      enabled: true
      type: pvc
      size: 1Gi
      storageClassName: longhorn
      accessModes:
        - ReadWriteOnce

    admin:
      existingSecret: grafana-auth
      userKey: admin-user
      passwordKey: admin-password

    extraSecretMounts:
      - name: auth
        secretName: grafana-auth
        mountPath: /etc/secrets/auth
        readOnly: true

    ingress:
      enabled: false

    sidecar:
      dashboards:
        enabled: false
      datasources:
        enabled: false

    grafana.ini:
      server:
        root_url: https://grafana.cbc.gewis.nl:8443

      analytics:
        reporting_enabled: false
        check_for_updates: false

      auth:
        disable_login_form: true

      auth.generic_oauth:
        enabled: true
        name: GEWISWG
        allow_sign_up: true
        client_id: "$__file{/etc/secrets/auth/keycloak-client-id}"
        client_secret: "$__file{/etc/secrets/auth/keycloak-client-secret}"
        scopes: "openid,email,profile,roles,offline_access"
        auth_url: "https://auth.gewis.nl/realms/GEWISWG/protocol/openid-connect/auth"
        token_url: "https://auth.gewis.nl/realms/GEWISWG/protocol/openid-connect/token"
        api_url: "https://auth.gewis.nl/realms/GEWISWG/protocol/openid-connect/userinfo"
        use_refresh_token: true

        email_attribute_path: "email"
        login_attribute_path: "username"
        name_attribute_path: "full_name"

        role_attribute_strict: true

        org_attribute_path: "roles"
        org_mapping: "GRAFANA-CBC-RO:CBC:Viewer GRAFANA-CBC-RW:CBC:Editor GRAFANA-ABC_CRM-RO:ABC-CRM:Viewer GRAFANA-ABC_CRM-RW:ABC-CRM:Editor GRAFANA-ABC_EOU-RO:ABC-EOU:Viewer GRAFANA-ABC_EOU-RW:ABC-EOU:Editor GRAFANA-ABC_DB-RO:ABC-DB:Viewer GRAFANA-ABC_DB-RW:ABC-DB:Editor GRAFANA-ABC_WEB-RO:ABC-WEB:Viewer GRAFANA-ABC_WEB-RW:ABC-WEB:Editor GRAFANA-ABC_NC-RO:ABC-NC:Viewer GRAFANA-ABC_NC-RW:ABC-NC:Editor GRAFANA-ABC_POS-RO:ABC-POS:Viewer GRAFANA-ABC_POS-RW:ABC-POS:Editor"

    livenessProbe:
      httpGet:
        path: /api/health
        port: 3000
    readinessProbe:
      httpGet:
        path: /api/health
        port: 3000
