apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kite-oidc
  namespace: kite
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: authentik
    kind: SecretStore
  target:
    name: kite-oidc
  data:
    - secretKey: client_secret
      remoteRef:
        key: kite/kite
        property: client_secret
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: kite-keys
  namespace: kite
spec:
  length: 64
  symbols: 0
  noUpper: false
  allowRepeat: true
  secretKeys:
    - JWT_SECRET
    - KITE_ENCRYPT_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kite-keys
  namespace: kite
spec:
  refreshPolicy: CreatedOnce
  target:
    name: kite-keys
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: kite-keys
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: kite-admin
  namespace: kite
spec:
  length: 64
  symbols: 0
  noUpper: false
  allowRepeat: true
  secretKeys:
    - password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kite-admin
  namespace: kite
spec:
  refreshPolicy: CreatedOnce
  target:
    name: kite-admin
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: kite-admin
