apiVersion: v1
kind: ServiceAccount
metadata:
  name: authentik
  namespace: kite
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: authentik
  namespace: kite
spec:
  provider:
    vault:
      server: http://openbao-active.openbao.svc:8200
      path: authentik
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: authentik-kite
          serviceAccountRef:
            name: authentik
