// Fullscreen wallpaper

Window.SetBackgroundTopColor(0, 0, 0);
Window.SetBackgroundBottomColor(0, 0, 0);

// Background

wallpaper_image = Image("wallpaper.png");

scale_x = Window.GetWidth() / wallpaper_image.GetWidth();
scale_y = Window.GetHeight() / wallpaper_image.GetHeight();
if (scale_x > scale_y) {
    cover_scale = scale_x;
} else {
    cover_scale = scale_y;
}

background_image = wallpaper_image.Scale(
    Math.Int(wallpaper_image.GetWidth() * cover_scale),
    Math.Int(wallpaper_image.GetHeight() * cover_scale)
);

background_sprite = Sprite();
background_sprite.SetImage(background_image);
background_sprite.SetX((Window.GetWidth() - background_image.GetWidth()) / 2);
background_sprite.SetY((Window.GetHeight() - background_image.GetHeight()) / 2);
background_sprite.SetZ(-100);
