---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare
  namespace: external-dns
spec:
  encryptedData:
    api-token: AgBGza3LxCoikEx2cKK39K9IaJvw+rlDVTwpy4yQX1vngdjIHkkyX2zH/gRosZSBsbGSLFPlQkTsv8PY1syNKpilIqU70LPXjSFluM5gsZJEt4QuUEGbwVoGSkXI3JxKgUhRghcqyHAe1F2xtcSumQbChD2gV5eRqAjzreFHkfvdA7qfX38YyHY5q8+WxkndK9Ypzs2nBy60R2dGANVtnT6ub+g8bw8m+OU1yTm5X8hes8rDZxqJ+Mmc64giJuS9GoirDpx7SYpsOhAz6nUpLT+UWWo+QR9U66tj0vBddMi2SawH9e18LLcfuPGai6kbe2kGvv5cJ/P7Qm4ikzu1Pa0q2LONeZCX/am2UeCokgZjSP7253s0fYh9dz3eKwTYdBtHuhPpHAG/FSMsBV/EmLrl8fh+secKvlbfF2MT45Byj2OCney4j5E6PhgGl5HWokUkqTPiiTm43IOriPRIzs3sAF/xERgICe06hOUEwUIqkWQoblgCJ0kd+Fx+GybjrZ2x/iUvPBTyjaRWWD/0vreZA6JxnL15SAER0NJS7gbdxcIoIbOsFsDnn9TLjXLwJ+F1rp3niuYXD9arcsI1OICJvpyiQtlbbXRSrUvS66E5fQU8QxwlIOWKMCkFZzhXYHTkNPkrVJLCuW5RnKowfw8WQ8wdR5ehe3i7XhOnguGYqGrfSC9PO3qzVO+5x3pSXfRkI//npUpWurhVEqzhQE0/QmhN9GQ4u7Ae8I8GiK/N2ueseh9gkKMVfJrUE0Wq6zphSHXlcg==
  template:
    metadata:
      name: cloudflare
      namespace: external-dns
