---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openbao-seal
  namespace: openbao
spec:
  encryptedData:
    key: AgA9i9LE4BWt/bXQ78LECAcALychLXRFgcwh0+FJi7aNw7tJiv+a07rexo0b2TgLzFc9Wq1ajx2bXdc+u08d/0BSV3/QNb+rFV4Sz24bMsKs714T9a7OWvS4xCs53Jhy37QTKWtiQxiip5iYF85rZmFwqlwmrjCutlOkkCArZBpbg7gbLmD0URX7rIY4QYeuKcZohBT14MbyAgEwgrF5+mGo2WItWUdkN6DswSkpR748F/rgdEp/UPooWD0Zo2eEWipu54ZsKJ9fAnTyfhiL/TMCJBUJol9+I4UPkoeBx7oZH2mb7nws5s+JKqfGGO82NfY+01bog9Q6wPUpjoJKv8wVbGWTV5/PTNP3GBZm8g35rRIH0iUcs+BSGZXvhbaGLDW/1oScmonLFpGJGpuIwEZcFiq6LA796RjKS4fRWRU891Ho/lhBTpABGeDAzkEsyj3kq65w2Gjo3KtMZl+WvBHFuI0++oYwtnd3oQ4cZoNhHfJAC+0hLen/haiolgpW+1VOxbAIV6VwCgaomv1Q35plEZSh2tlmIp1tzSiIFQOyHZw4dFUcULwvGdbDmCEcJhGB63zfMyX9Kvn3ItcD+TX3W5Cke4oqMTYyArYsXlR7pL9Lv4QPuXc1waYgEhh9uxH2Kio+r6l4r1OgNjwgn7y5MaxQGNaiOhFaOZnt59SUdVdfphkhFg5ABEbcs6hlZ4mW9q+OJ4wy0PS1FIDrSNKVBovJqWyVIfPMRjxsCjLaf+AaSa45acEFIgguYQ==
  template:
    metadata:
      name: openbao-seal
      namespace: openbao
